### ISSUE TITLE
Broken trepan import in v0.8.4

### ISSUE THREAD

**Issue by dangirsh** [rocky/python3-trepan#10]
In a fresh Python 3.5.2 virtual environment on Ubuntu 16.04:

```
> pip install trepan3k==0.8.4
> trepan3k
Traceback (most recent call last):
  File "/home/dan/.virtualenvs/python3/bin/trepan3k", line 7, in <module>
    from trepan.cli import main
ImportError: No module named 'trepan'
```

Going back to 0.8.3 makes the issue disappear.

**Comment by rocky** [comment]
Thanks for the report.

**Comment by mroll** [comment]
I'm also seeing this on MacOS Sierra.

```(bn-api) mroll@fool:~/.projects/bn-api ∂ trepan3k main.py
Traceback (most recent call last):
  File "/Users/mroll/.envs/bn-api/bin/trepan3k", line 7, in <module>
    from trepan.cli import main
ModuleNotFoundError: No module named 'trepan'```

**Comment by rocky** [comment]
I can't figure out right now what's different between 0.8.3 and 0.8.4 that would break this. 

So for now I've hidden the 0.8.4 release. (Personally, I like the deparsing improvements in 0.8.4, but I suppose one an get that running from the source as I generally do.)

**Comment by yssource** [comment]
the same problem happened to me also

**Comment by rocky** [comment]
@yssource Hmmm I thought 0.8.4 has been hidden so how is it that you've been able to install it?

**Comment by yssource** [comment]
@rocky 
Previously, the problem happened to me when `pip install -U trepan3k`. 
Now, `git clone your_repo` and then `pip install -e .` works for me.
`trepan 0.8.5` is good.

**Comment by 1dream** [comment]
Had the same problem and solved it like @yssource

**Comment by Suor** [comment]
It is still not hidden. Installed it via `pip install trepan3k`.

**Comment by rocky** [comment]
Hmm. 0.8.5 is gone! 

I've removed the last remaining source in trepan3k from 0.8,4. I will be adding a 0.8.6 to get in new versions of uncompyle6 soon.

**Comment by rocky** [comment]
@Suor 0.8.6 is out and 0.8.4 is should be truly gone. See if this addresses the problems you've been having.
