### ISSUE TITLE
info threads?

### ISSUE THREAD

**Issue by agala-stratio** [rocky/python3-trepan#12]
Hi, 
I am trying to show info from threads (**info threads**) by using trepan3k 0.8.6 and debugging python3.5 programs. (command: **trepan3k threads_sample.py**)

I only get the _Mainthread_.

How can I show the threads info for a program? such as:
#############################################################
import threading
def worker():
    """thread worker function"""
    print('Worker')

threads = []
for i in range(5):
    t = threading.Thread(target=worker)
    threads.append(t)
    t.start()
#############################################################

Regards!

**Comment by rocky** [comment]
Yes, `info threads` is one command to show threads. And when there is threading going on a`backtrace` command detects that and shows information about the other threads.

The issue tracker is not suited for basic help questions like this. Ask your question in another venue like stackoverflow.com or quoa.com where others are likely to see the question and assist and where any answers and comments given others will see in the future.

Thanks.
