### ISSUE TITLE
Universal wheel breaks for Python 3.8.

### ISSUE THREAD

**Issue by jaccarmac** [rocky/python3-trepan#43]
Because trepan3k tries to use decompyle3 for Pythons 3.7 and 3.8, the universal wheel doesn't work, allowing the debugger to start but with a missing import error message and no elaboration. Manually installing decompyle3 fixes things.

**Comment by rocky** [comment]
Thanks for the report. I have yanked the universal wheel. Next release I'll make specialized wheels.
