### ISSUE TITLE
Step into a child process?

### ISSUE THREAD

**Issue by Michael-F-Ellis** [rocky/python3-trepan#5]
Can trepan3k step into a child process started with multiprocessing.Process()? I tried stepping down into proc.start() in the tiny example below, but can't seem to find the fork() call. Setting a breakpoint in child() doesn't work, either.  

```
import time
from multiprocessing import Process

def child():
    while True:
        print("I am the child")
        time.sleep(10)

proc = Process(target=child)
proc.start()
proc.join() 
``` 

Thanks!

**Comment by rocky** [comment]
The issues trepan3k has with forking is the same as pdb, ipdb, and a host of other Python debuggers. Google around and you'll see it a common problem.

I am not sure about the specifics other than it is probably deep. Like many things, there is probably fragile hackery that possibly could be done, in the debugger side, but more likely an easier change would be to the Python runtime. 

What most people do then is to modify the code to force a stop like this: 

```
first_time = True
def child():
    while True:
      if first_time: 
          from trepan.api import debug; debug()
          first_time False
        print("I am the child")
        time.sleep(10)
```
